const sql = require('better-sqlite3');
const db = sql('planets.db')


const planetsDetails = [
  {
    title: "Mercury",
    slug: "mercury",
    image: "/mercury.png",
    summary:
      "Mercury, the smallest planet in the solar system, is the closest to the Sun. Despite being so near to the Sun, it is not the hottest planet. Mercury has extreme temperature swings due to its lack of atmosphere, which means the surface can reach temperatures of 427°C (800°F) during the day and plunge to -173°C (-280°F) at night. Its surface is rocky and cratered, similar to the Moon, as it has no atmosphere to protect it from impacts.",
    details: {
      dimension: "4,880 km (diameter)",
      rotation: "59 Earth days",
      orbit: "88 Earth days",
      facts: [
        'Mercury has no moons, making it unique among the inner planets.',
        "Mercury's solar day (sunrise to sunrise) lasts 176 Earth days, which is much longer than its rotation period (59 Earth days) or its orbital period (88 Earth days).",
        "Mercury is the fastest planet in the solar system, traveling at an average speed of 47 km/s around the Sun.",
        "Mercury has no atmosphere, but it has a thin exosphere made up of atoms blasted off its surface by the solar wind.",
        "Despite being closest to the Sun, Mercury isn't the hottest planet—that title goes to Venus due to its thick atmosphere.",
        "Mercury's surface is marked by craters from constant bombardment, and it has a very thin exosphere made of oxygen, sodium, hydrogen, helium, and potassium.",
        "Mercury experiences extreme temperature variations because it has almost no atmosphere to retain heat.",
        "In the future, Mercury might become the target for scientific exploration with proposed missions focused on understanding its surface and proximity to the Sun."
      ],
    },
  },
  {
    title: "Venus",
    slug: "venus",
    image: "/venus.png",
    summary:
      "Venus, Earth's “sister planet,” has a similar size and composition but is far more hostile. Its thick, toxic atmosphere traps heat through the greenhouse effect, making it the hottest planet in the solar system. The planet's surface is hidden by clouds of sulfuric acid, and its slow retrograde rotation means that a day on Venus lasts longer than a year.",
    details: {
      dimension: "12,104 km",
      rotation: "243 Earth days",
      orbit: "225 Earth days",
      facts: [
        "Venus has a thick atmosphere of carbon dioxide, with surface pressure 92 times that of Earth.",
        "Its surface temperature is a scorching 475°C (900°F), making it the hottest planet in the solar system.",
        "Venus rotates in the opposite direction of most planets (retrograde rotation).",
        "A day on Venus (243 Earth days) is longer than longer than its rotation period (225 Earth days).",
        "Venus is covered with volcanic plains and has over 1,600 major volcanoes.",
        "The planet's thick clouds reflect 70% of sunlight, giving it a bright, yellowish appearance from space.",
        "In the future, missions like NASA's VERITAS are planning to explore Venus to understand its geologic history and its potential for past habitability."
      ],
    },
  },
  {
    title: "Earth",
    slug: "earth",
    image: "/earth.png",
    summary:
      "Earth is the third planet from the Sun and the only one known to support life. With abundant liquid water, a stable climate, and a breathable atmosphere composed mostly of nitrogen and oxygen, Earth is uniquely suited for life. The planet has a dynamic surface with continents and oceans, and its atmosphere plays a crucial role in regulating temperature and protecting the planet from harmful radiation. Earth's moon, a large natural satellite, plays a significant role in stabilizing Earth's axial tilt and contributing to ocean tides.",
    details: {
      dimension: "12,742 km (diameter)",
      rotation: "24 hours",
      orbit: "365.25 days",
      facts: [
        "Earth's surface is 71% water, with oceans regulating the planet's temperature.",
        "Earth's atmosphere is composed primarily of nitrogen (78%) and oxygen (21%).",
        "The planet has a magnetic field generated by its molten core, protecting it from solar radiation.",
        "Earth is the densest planet in the solar system.",
        "Earth has an estimated 8.7 million species of plants and animals, though many are still undiscovered.",
        "Earth's axis tilt (23.5°) causes the seasons as the planet orbits the Sun.",
        "Earth's magnetic poles have reversed many times in the past, with the North and South Poles switching places.",
        "The Moon is slowly drifting away from Earth, at a rate of about 3.8 cm per year. Over billions of years, this could change the way Earth experiences time and its tides.",
        "In the future, Earth is likely to experience climate change impacts, and missions like SpaceX's Starship aim to help humanity become a multi-planet species, with Mars being the most likely candidate for future colonization."
      ],
    },
  },
  {
    title: "Mars",
    slug: "mars",
    image: "/mars.png",
    summary:
      "Mars, the 'Red Planet' is known for its reddish hue, caused by iron oxide (rust) on its surface. Mars once had liquid water on its surface and may have had conditions suitable for life billions of years ago, now has polar ice caps made of water and carbon dioxide. Mars is often a target for human exploration and potential colonization.",
    details: {
      dimension: "6,779 km (diameter)",
      rotation: "24.6 hours",
      orbit: "687 Earth days",
      facts: [
        
        "Its thin atmosphere is primarily carbon dioxide, making it incapable of supporting human life without aid.",
        "Mars experiences dust storms that can engulf the entire planet.",
        "Mars has two moons, Phobos and Deimos, which are thought to be captured asteroids.",
        "Olympus Mons on Mars is a shield volcano that is about 21.9 km tall, making it the largest volcano in the solar system.",
        "Mars has the largest canyon system in the solar system, Valles Marineris, which is more than 4,000 km long and up to 7 km deep.",
        "Mars is the focus of several future missions, such as NASA's Artemis program, which will eventually send humans to explore the planet."
      ],
    },
  },
  {
    title: "Jupiter",
    slug: "jupiter",
    image: "/jupiter.png",
    summary:
      "Jupiter is the largest planet in the solar system and a gas giant made mostly of hydrogen and helium. Its Great Red Spot is a massive storm that has been raging for over 300 years. Jupiter has a strong magnetic field and dozens of moons, with Ganymede being the largest moon in the solar system. It's a fascinating target for future exploration, particularly its moons, which might harbor subsurface oceans.",
    details: {
      dimension: "139,820 km (diameter)",
      rotation: "9.9 hours",
      orbit: "11.86 Earth years",
      facts: [
        "Jupiter is so massive that it has over 300 times the mass of Earth.",
        "Jupiter has 92 known moons, including Ganymede, which is larger than the planet Mercury.",
        "Its magnetic field is the strongest of any planet in the solar system.",
        "Jupiter emits more heat than it receives from the Sun due to internal processes.",
        "Jupiter's rapid rotation causes it to have a strong equatorial bulge, and its fast winds create high-speed jet streams.",
        "Future missions, like NASA's Juno spacecraft and ESA's Jupiter Icy Moons Explorer (JUICE), will continue to study Jupiter and its moons."
      ],
    },
  },
  {
    title: "Saturn",
    slug: "saturn",
    image: "/saturn.png",
    summary:
      "Saturn is best known for its breathtaking ring system, which is composed mainly of ice and rock particles. The planet is a gas giant, similar to Jupiter, and is made primarily of hydrogen and helium. Saturn has 146 confirmed moons, with Titan being the largest, and is the second-largest planet in the solar system. Titan, with its thick atmosphere and liquid methane lakes, is considered one of the most Earth-like moons in the solar system.",
    details: {
      dimension: "116,460 km (diameter)",
      rotation: "10.7 hours",
      orbit: "29.5 Earth years",
      facts: [
        "Saturn's rings are made up of ice and rock particles ranging in size from dust to mountains.",
        "Saturn is the least dense planet, capable of floating in water.",
        "Winds on Saturn can reach speeds of up to 1,800 km/h (1,118 mph).",
        "It takes Saturn nearly 30 Earth years to complete one orbit around the Sun.",
        "Titan, Saturn's largest moon, has a thick nitrogen-rich atmosphere and liquid methane lakes, raising the possibility of microbial life in the future.",
        "Future missions, like NASA's Dragonfly, are focused on exploring Titan for its potential to support life."
      ],
    },
  },
  {
    title: "Uranus",
    slug: "uranus",
    image: "/uranus.png",
    summary:
      "Uranus is unique due to its extreme axial tilt—about 98 degrees—causing the planet to essentially roll around the Sun on its side. It's an ice giant composed of water, ammonia, and methane, and has a pale blue appearance due to methane in its atmosphere. Uranus has 27 moons and a faint ring system, and its mysterious atmosphere and tilt have made it a target for future exploration.",
    details: {
      dimension: "50,724 km (diameter)",
      rotation: "17.2 hours",
      orbit: "84 Earth years",
      facts: [
        "Uranus has a very tilted axis, which makes its seasons extremely long and extreme, with 42 Earth years of daylight and 42 Earth years of darkness.",
        "Uranus has 27 known moons, with Titania being the largest and Miranda, which has some of the solar system's most extreme terrain features.",
        "The planet's methane-rich atmosphere gives it a pale blue color, and it has a cold, icy interior.",
        "Uranus was the first planet discovered with a telescope, in 1781 by William Herschel.",
        "The planet's rings are faint and mostly made of ice and dust particles.",
        "Future missions, like NASA's proposed Uranus Orbiter and Probe, aim to explore the planet's unique atmosphere and system."
      ],
    },
  },
  {
    title: "Neptune",
    slug: "neptune",
    image: "/neptune.png",
    summary:
      "Neptune is the eighth and farthest planet from the Sun. Known for its deep blue color, Neptune is another ice giant composed mostly of hydrogen, helium, and methane. Its strong winds make it the windiest planet in the solar system, and it has a system of rings, along with 14 known moons. Triton, Neptune's largest moon, has geysers that suggest an active, subsurface ocean.",
    details: {
      dimension: "49,244 km (diameter)",
      rotation: "16.1 hours (rotation period)",
      orbit: "165 Earth years (orbital period around the Sun)",
      facts: [
        "Neptune has the fastest winds in the solar system, reaching speeds of up to 2,100 km/h (1,300 mph).",
        "The planet appears deep blue due to the presence of methane in its atmosphere.",
        "Neptune has 14 known moons, with Triton being the largest and having a retrograde orbit.",
        "Neptune's Great Dark Spot is a massive storm similar to Jupiter's Great Red Spot.",
        "It was the first planet predicted by mathematical calculations before being observed in 1846.",
        "Neptune's rings are faint and made of ice particles, dust, and methane clumps.",
        "NASA's Voyager 2 is the only spacecraft to have visited Neptune, but future missions may explore the planet's atmosphere and moons."
      ],
    },
  },
];

// planets table
db.prepare(`
    CREATE TABLE IF NOT EXISTS planets (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        slug TEXT NOT NULL UNIQUE,
        title TEXT NOT NULL,
        image TEXT NOT NULL,
        summary TEXT NOT NULL
    );
`).run();

db.prepare(`
    CREATE TABLE IF NOT EXISTS planet_details (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        planet_id INTEGER NOT NULL,
        dimension TEXT NOT NULL,
        rotation TEXT NOT NULL,
        orbit TEXT NOT NULL,
        FOREIGN KEY (planet_id) REFERENCES planets (id)
    );
`).run();

db.prepare(`
    CREATE TABLE IF NOT EXISTS planet_facts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        planet_id INTEGER NOT NULL,
        fact TEXT NOT NULL,
        FOREIGN KEY (planet_id) REFERENCES planets (id)
    );
`).run();

const insertPlanetStmt = db.prepare(`
    INSERT INTO planets (slug, title, image, summary)
    VALUES (?, ?, ?, ?)
`)

const insertDetailsStmt = db.prepare(`
    INSERT INTO planet_details (planet_id, dimension, rotation, orbit)
    VALUES (?, ?, ?, ?)
`)

const insertFactStmt = db.prepare(`
    INSERT INTO planet_facts ( planet_id, fact)
    VALUES(?, ?)
`)


function initData(){
   for(const planet of planetsDetails) {
        const result = insertPlanetStmt.run(planet.slug, planet.title, planet.image, planet.summary);
        const planetId = result.lastInsertRowid;

        insertDetailsStmt.run(planetId, planet.details.dimension, planet.details.rotation, planet.details.orbit);

        for( const fact of planet.details.facts){
            insertFactStmt.run(planetId, fact);
        }
    }
    console.log('Data inserted successfully!');
    
}

initData();